version: "3.9"

services:
  app:
    image: space 
    ports:
      - "8000:8000"
    command: python src/manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/space
    depends_on:
      - db

  db:
    image: postgres:13.4-alpine 
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app_test:
    image: space_test
    ports:
      - "8000:8000"
    environment:
      - DB_URL=postgres://postgres:postgres@db_test:5432/space_test
      - SECRET_KEY=dummy
      - DEBUG=True
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/space
    depends_on:
      - db_test

  db_test:
    image: postgres:13.4-alpine 
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres 
      - POSTGRES_PASSWORD=postgres 
      - POSTGRES_DB=space_test
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  postgres_test_data:
