version: "3.9"

services:
  app:
    image: space 
    ports:
      - "8000:8000"
    command: python src/manage.py runserver 0.0.0.0:8000
    environment: &environment
      - DJANGO_DB_URL=postgis://postgres:postgres@db:5432/space
      - DJANGO_SECRET_KEY=dummy
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/space
    depends_on:
      - db

  db:
    image: postgres:13.4-alpine 
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
