# Generated by Django 3.2.6 on 2021-08-29 00:46

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldWorker',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('function', models.CharField(choices=[('HARVEST', 'HARVEST'), ('PRUNING', 'PRUNING'), ('SCOUTING', 'SCOUTING'), ('OTHER', 'OTHER')], default='OTHER', max_length=15)),
            ],
            options={
                'db_table': 'field_worker',
            },
        ),
    ]
